name: PR-Greeting
on: [pull_request]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Post PR message
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "PR Raised"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
